### PR TITLE
Move ember-sinon to dependencies

### PR DESCRIPTION
**Pull request by simonihmig**

### CODE REVIEW

**Comment by simonihmig** [comment]
The failing tests come from `ember-sinon` having dropped node 4 support in 2.2.0 without bumping the major version... 🙄

I guess this addon can also drop, and release as 0.3.0?

**Comment by rwjblue** [comment]
Ya

**Comment by scalvert** [comment]
Agree.

**Comment by scalvert** [comment]
@simonihmig feel free to make that change in this PR and I'll release.

**Comment by scalvert** [comment]
Going to close this as I don't think it's an issue anymore.

**Pull request closed without merging**
